import axios from "./axios";

const requests = {
  validateLogin: `/ValidateLogin`,
  getPermissionTemplate: `/GetPermissionTemplate`,
  getTemplateUserMapping: `/GetTemplateUserMapping`,
  getAllUsers: '/GetAllUsers',
  validateTemplate: '/GetAllUsers',
  getDataSourceSetting: '/GetDataSourceSetting',
  getColumnForDataSourceSetting: '/GetColumnForDataSourceSetting',
  formDashboardVersion: '/FormDashboardVersion',
  getActive: '/GetActive',
  copyAsNewForm: '/CopyAsNewForm',
  exportFormAsJson: '/ExportFormAsJson',
  getMasterFields: '/GetMasterFields',
  getForms: '/GetForms',
  getFormPreview: '/GetFormPreview',
  getFormSubmitted: '/GetFormSubmitted',
  deleteForm: '/DeleteForm',
  deleteFormVersion: '/DeleteFormVersion',
  validateDeletionForm: '/ValidateDeletionForm',
  getResultsView: '/GetResultsView',
  getToolBox: '/GetToolBox',
  getRatingsInForm: '/GetRatingsInForm',
  getInfoPromptForms: '/GetInfoPromptForms',
  getInfoPromptFormVersions: '/GetInfoPromptFormVersions',
  getAllMapped: '/GetAllMapped',
  getMasterChecklists: '/GetMasterChecklists',
  getChecklistItems: '/GetChecklistItems',
  removeChecklist: '/RemoveChecklist',
  deleteChecklistItem: '/DeleteChecklistItem',
  getMasterAssessmentsForChecklist: '/GetMasterAssessmentsForChecklist',
  deleteChecklistGroup: '/DeleteChecklistGroup',
  copyChecklist: '/CopyChecklist',
  validateDeletionMasterChecklist: '/ValidateDeletionMasterChecklist',
  validateDeletionChecklistItem: '/ValidateDeletionChecklistItem',
  getMasterAssessment: '/GetMasterAssessment',
  removeAssesment: '/RemoveAssesment',
  validateDeletionMasterAssessment: '/ValidateDeletionMasterAssessment',
  copyAssessment: '/CopyAssessment',
  getAssesmentTypeOptions: '/GetAssesmentTypeOptions',
  removeAssessmentOption: '/RemoveAssessmentOption',
  validateLogin: '/ValidateLogin',
  getFormDescription: '/GetFormDescription',
  getFormPassword: '/GetFormPassword',
  getValidatePassword: '/GetValidatePassword',
  getFormTemplates: '/GetFormTemplates',
  getGroupWiseTemplates: '/GetGroupWiseTemplates',
  getTemplatePreview: '/GetTemplatePreview',
  deleteTemplate: '/DeleteTemplate',
  getMasterGroups: '/GetMasterGroups',
  deleteMasterGroups: '/DeleteMasterGroups',
  getMasterReasonCode: '/GetMasterReasonCode',
  deleteMasterReasonCode: '/DeleteMasterReasonCode',
  getMasterReasonCodeOptions: '/GetMasterReasonCodeOptions',
  removeMasterReasonCodeOption: '/RemoveMasterReasonCodeOption',
  validateMasterReasonCode: '/ValidateMasterReasonCode',
  getMasterModuleMapping: '/GetMasterModuleMapping',
  getMasterItemRepository: '/GetMasterItemRepository',
  validateDeletionItemRepository: '/ValidateDeletionItemRepository',
  removeMasterItemRepository: '/RemoveMasterItemRepository',
  generateStaticForm: '/GenerateStaticForm',
  getMasterGeneralRepository: '/GetMasterGeneralRepository',
  validateDeletionGeneralRepository: '/ValidateDeletionGeneralRepository',
  removeMasterGeneralRepository: '/RemoveMasterGeneralRepository',
  getMasterGeneralItemDashboard: '/GetMasterGeneralItemDashboard',
  removeMasterGeneralItemDashboard: '/RemoveMasterGeneralItemDashboard',
  validateGeneralItemDashboard: '/ValidateGeneralItemDashboard',
  getVersionForm: '/GetVersionForm',
  getPermission: '/GetPermission',
  getPermissionTemplate: '/GetPermissionTemplate',
  removePermissionTemplate: '/RemovePermissionTemplate'
};

async function PrepareRequest(path) {
  let response = await axios.get(`${path}`);
  return response;
}

export { requests, PrepareRequest };
